// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PB01.Infrastructure.Data;
using System;

namespace PB01.Infrastructure.Migrations
{
    [DbContext(typeof(BemPatrimonialContext))]
    [Migration("20180425044206_ConfiguraTodasClasses")]
    partial class ConfiguraTodasClasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PB01.AplicationCore.Entity.Auditoria", b =>
                {
                    b.Property<int>("AuditoriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Aprovado");

                    b.Property<DateTime>("Data");

                    b.HasKey("AuditoriaId");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("PB01.AplicationCore.Entity.BemPatrimonial", b =>
                {
                    b.Property<int>("BemPatrimonialId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCadastro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NumeroTombo")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("BemPatrimonialId");

                    b.ToTable("BemPatrimonial");
                });

            modelBuilder.Entity("PB01.AplicationCore.Entity.Categoria", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("PB01.AplicationCore.Entity.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("EnderecoId");

                    b.ToTable("Endereço");
                });

            modelBuilder.Entity("PB01.AplicationCore.Entity.Responsavel", b =>
                {
                    b.Property<int>("ResponsavelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.HasKey("ResponsavelId");

                    b.ToTable("Responsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
